language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
