language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/coveralls
